[package]
name = "gha-indie-worker-sidecar"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Sidecar for GHA Indie Worker."
repository = "https://github.com/gha-indie-worker/gha-indie-worker-sidecar.rs"
readme = "README.md"

[lib]
name = "gha_indie_worker_sidecar"
path = "src/lib.rs"

[[bin]]
name = "ghaiw-sidecar"
path = "src/main.rs"

[dependencies]
gha-indie-worker-interfaces = { git = "https://github.com/gha-indie-worker/gha-indie-worker-interfaces", rev = "7165a361462e624195e91cf88ec472b7d6e9c1da" }
ores-otel-sidecar = { git = "https://github.com/ores-otel/ores-otel-sidecar.rs", rev = "aad578349dd546445e5fda2f20b9310a72fa1f23" }
serde_json = "1"

[lints.rust]
unsafe_code = "forbid"
